version: 2

sources:
  - name: raw_data_dbx
    database: dev_abhi_catalog  
    schema: source_abhi  
    tables:
      - name: dim_customer
        description: "Customer dimension table"
        columns:
          - name: customer_sk
            description: "Surrogate key for customer"
          - name: customer_code
            description: "Business code for customer"
          - name: first_name
            description: "Customer's first name"
          - name: last_name
            description: "Customer's last name"
          - name: gender
            description: "Gender of the customer"
          - name: email
            description: "Customer's email address"
          - name: phone
            description: "Customer's phone number"
          - name: loyalty_tier
            description: "Loyalty tier of the customer"
          - name: signup_date
            description: "Date when the customer signed up"

      - name: dim_date
        description: "Date dimension table"
        columns:
          - name: date_sk
            description: "Surrogate key for date"
          - name: date
            description: "Date value"
          - name: day
            description: "Day of the month"
          - name: month
            description: "Month number"
          - name: month_name
            description: "Month name"
          - name: quarter
            description: "Quarter number"
          - name: year
            description: "Year"
          - name: day_of_week
            description: "Day of the week number"
          - name: day_name
            description: "Day name"
          - name: is_weekend
            description: "Is weekend flag"
          - name: is_month_end
            description: "Is month end flag"
          - name: is_month_start
            description: "Is month start flag"
          - name: is_quarter_end
            description: "Is quarter end flag"
          - name: is_quarter_start
            description: "Is quarter start flag"

      - name: dim_product
        description: "Product dimension table"
        columns:
          - name: product_sk
            description: "Surrogate key for product"
          - name: product_code
            description: "Business code for product"
          - name: product_name
            description: "Name of the product"
          - name: department
            description: "Department of the product"
          - name: category
            description: "Category of the product"
          - name: supplier_sk
            description: "Supplier surrogate key"
          - name: list_price
            description: "List price of the product"
          - name: uom
            description: "Unit of measure"

      - name: dim_store
        description: "Store dimension table"
        columns:
          - name: store_sk
            description: "Surrogate key for store"
          - name: store_code
            description: "Business code for store"
          - name: store_name
            description: "Name of the store"
          - name: city
            description: "City where the store is located"
          - name: state_province
            description: "State or province"
          - name: region
            description: "Region"
          - name: country
            description: "Country"
          - name: open_date
            description: "Store opening date"
          - name: sq_ft
            description: "Store size in square feet"

      - name: fact_returns
        description: "Returns fact table"
        columns:
          - name: sales_id
            description: "Sales transaction ID"
          - name: date_sk
            description: "Date surrogate key"
          - name: store_sk
            description: "Store surrogate key"
          - name: product_sk
            description: "Product surrogate key"
          - name: returned_qty
            description: "Quantity returned"
          - name: return_reason
            description: "Reason for return"
          - name: refund_amount
            description: "Refund amount"

      - name: fact_sales
        description: "Sales fact table"
        columns:
          - name: sales_id
            description: "Sales transaction ID"
          - name: date_sk
            description: "Date surrogate key"
          - name: store_sk
            description: "Store surrogate key"
          - name: product_sk
            description: "Product surrogate key"
          - name: customer_sk
            description: "Customer surrogate key"
          - name: promotion_sk
            description: "Promotion surrogate key"
          - name: quantity
            description: "Quantity sold"
          - name: unit_price
            description: "Unit price"
          - name: gross_amount
            description: "Gross amount"
          - name: discount_amount
            description: "Discount amount"
          - name: net_amount
            description: "Net amount"
          - name: payment_method
            description: "Payment method"